### ISSUE TITLE
Possible issue with ansible v2.3.1.0 

### ISSUE THREAD

**Issue by pablodav** [AlbanAndrieu/ansible-pagespeed#1]
Running today this role I got: 

```
ERROR! 'ansigenome_info' is not a valid attribute for a RoleMetadata

The error appears to have been in '/etc/ansible/roles/apache_pagespeed/meta/main.yml': line 4, column 1, but may
be elsewhere in the file depending on the exact syntax problem.
```

Deleting `ansigenome_info` from  meta file resolves the issue. 

What is `ansigenome_info` for? Is it requirement for some ansible version?

**Comment by AlbanAndrieu** [comment]
ansigenome_info is used by tools https://github.com/nickjj/ansigenome/ in order to help creating the README.
This info has been moved to file https://github.com/AlbanAndrieu/ansible-pagespeed/blob/master/meta/ansigenome.yml

And I have created a new release v1.0.1

**Comment by pablodav** [comment]
Thanks you!
